[package]
name = "alloc_miri_test"
version = "0.0.0"
autotests = false
autobenches = false
edition = "2021"

[lib]
name = "alloc_miri_test"
path = "../library/alloc/src/lib.rs"

[features]
# Empty this crate to avoid two copies of liballoc.
# See https://github.com/rust-lang/miri-test-libstd/issues/4.
default = ["miri-test-libstd"]
miri-test-libstd = []

[dependencies]

[dev-dependencies]
rand = "0.7"
rand_xorshift = "0.2"

[[test]]
name = "collectionstests"
path = "../library/alloc/tests/lib.rs"
